osx_image: xcode7.3
language: objective-c
script:
 - set -o pipefail && xcodebuild clean build test -workspace LegofySwift.xcworkspace -scheme LegofySwift -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 5,OS=8.4" -enableCodeCoverage YES
 - bash <(curl -s https://codecov.io/bash) -J 'LegofySwift'
